name: local_auth_example
description: Demonstrates how to use the local_auth plugin.

dependencies:
  flutter:
    sdk: flutter
  flutter_local_auth_invisible:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.0.0
